[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "my-assistant"
version = "0.0.1"
description = ""
authors = []
readme = "README.md"

[tool.langserve]
export_module = "my_assistant"
export_attr = "chain"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
langchain-core = "^1.0.0" 
langchain = "^1.0.0"
langchain-openai = "^1.1.0" 
langserve = "^0.3.0"
langsmith = "^0.4.0" 
langchain-community = "^0.4.1"

[tool.poetry.group.dev.dependencies]
fastapi = "^0.104.0"
sse-starlette = "^1.6.5"
pytest = "^9.0.1"